server:
  port: ${PORT:5000}


spring:
  main:
    banner-mode: off

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/rest_test?useLegacyDatetimeCode=false&serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:123456}

  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    show-sql: false
